project:
  type: website
  output-dir: "docs"

website:
  title: "cooperative-cobra"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Notes"
        menu:
          - text: "Module 1"
            href: Notes/Module1-TensorBasics.qmd
          - text: "Module 2"
            href: Notes/Module2-LinearRegression.qmd
          - text: "Module 3"
            href: Notes/Module3-LogisticRegression.qmd
      - text: "Assignments"
        menu:
          - text: "1. Boston Housing regression"
          - href: Assignments/Assignment1-BostonHousing.qmd
    right:
      - icon: github
        href: https://github.com/wzbillings/cooperative-cobra/
      - icon: arrow-90deg-up
        href: https://wzbillings.com/

format:
  html:
    theme:
      light: pulse
      dark: vapor
    css: styles.css
    mainfont: "Atkinson Hyperlegible"
    monofont: "Anonymous Pro"
    toc: true
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=Atkinson+Hyperlegible|Anonymous+Pro" type="text/css"/>

execute: 
  freeze: auto



