---
title: "Zane's Pytorch Adventure"
execute: 
  freeze: false
---

Welcome! If you wanted to see my notes or projects where I learned about
Pytorch for the first time, you're in the right place! Hopefully the
navbar above will get you where you need to go.

In order to learn Pytorch, I decided to follow along with this
[free 12 hour course](https://www.freecodecamp.org/news/free-deep-learning-with-pytorch-live-course/)
offered by `freeCodeCamp`. I also considered their
[26 hour course](https://www.freecodecamp.org/news/learn-pytorch-for-deep-learning-in-day/),
but my goal was to learn Pytorch in a few days so I could put it on an
internship application. Maybe when I have 26 spare hours (hahahahahaha. But,
like, I guess I had 12 hours for this one so it's not that much more…) I'll
go back and see what I can learn from that one as well.

Note that I don't plan to get the little certificate that the host, Jovian.ml,
offers for this class. In order to get the little certificate, you're required
to use their code and their platform and I don't really like that. I'd rather
use **my** platform the way I want to, and everyone will still be able to see
what I did.

Right now, there's not
much else I can think of to add on this place (probably a directory of
projects once there's more to show), so I've included the same basic information
you'd find on the main GitHub page.

{{< include README.qmd >}}

<!-- END OF FILE -->
